-- ESTUDOS DE PROCEDURES COM PARAMETROS  USANDO A TABELA CLIENTES NO BANCO DE DADOS PEDIDOSDB

--CRIANDO UMA PROCEDURE COM PARAMETRO 
-- SMALLINT SIGNIFICA PEGAR OS VALORES QUE JÁ EXIXSTEM NO BANCO DE DADOS
CREATE PROCEDURE CLIENTE_PARAMETRO
(@ID  SMALLINT)
AS
SELECT NOME,ENDERECO,CIDADE,BAIRRO FROM CLIENTES WHERE CODCLIENTE = @ID

EXEC CLIENTE_PARAMETRO 2

-- ALTERAR UMA PROCEDURE COLOCANDO PARAMETROS 
-- ESSE PROCEDIMENTO É NECESSARIO EXECUTAR COM PASSANDO 2 PARAMETROS, 1 INT 2 VARCHAR 
ALTER PROCEDURE TESTE
(@PARAMETRO1 AS INT, 
@PARAMETRO2 AS VARCHAR(20))
AS
SELECT @PARAMETRO1 AS NUMERO, @PARAMETRO2 AS NOME

EXEC TESTE 3, 'CINTHIA'

SELECT * FROM CLIENTES

