--TABELAS TEMPORARIAS 

CREATE TABLE #TMP_TEMPORARIA(
	NOME VARCHAR(20),
	IDADE INT
	);

	INSERT INTO #TMP_TEMPORARIA (NOME,IDADE) VALUES('CINTHIA',21);

	SELECT * FROM #TMP_TEMPORARIA

	--FAZENDO INSERT DA TABELA TBLCLIENTE E CRIANDO UMA TEMPORARIA 
	SELECT  * INTO #TMP_DADOS FROM tblCliente

	SELECT * FROM #TMP_DADOS