--ESTUDOS DE BETWEEN ...AND   BETWEEN = ENTRE 
/*
EXEMPLO:
SELECT COLUNAS FROM TABELA WHERE COLUNA BETWEEN VALOR1 AND VALOR2

*/
SELECT * FROM CLIENTES

SELECT CODCLIENTE, NOME FROM CLIENTES WHERE CODCLIENTE BETWEEN 3 AND 6 


SELECT *FROM PEDIDOS
INSERT INTO PEDIDOS VALUES(3,'20201131',4,'CREDITO')

SELECT C.NOME, P.CODPEDIDO,P.PRAZO_ENTREGA
FROM CLIENTES AS C INNER JOIN PEDIDOS AS P ON C.CODCLIENTE = P.CODPEDIDO
WHERE P.PRAZO_ENTREGA BETWEEN 2 AND 5