-- CURSO INTERMEDIARIO SQL SERVER

--FUNÇÕES DE TEMPO

--DATA ATUAL
SELECT CAST(GETDATE() AS DATE) 

--DIFERENÇA/ COMPARAÇÃO DE DATAS	
	SELECT DATEDIFF( DAY,'19990131',GETDATE())

--DATA E HORA ADICIONAR/DIMINUIR TEMPO
SELECT	DATEADD(YEAR,-1, GETDATE())

--DIAS DA SEMANA EM NUMEROS
SELECT DATEPART(WEEKDAY, GETDATE())

--BETWEEN = ENTRE INTERVALO DE TEMPO

--FORMAT FORMATAR  A DATA
SELECT FORMAT(CAST(GETDATE()AS DATE),'dd/MM/yyyy')