-- ESTUDOS DE PARAMNTO DE SAIDA 

-- ESSA PROCEDURE SOLICITA QUE O USUARIO DIGITE UM NUMERO DE PARAMENTRO E SAI OUTRO VALOR (QUE ESTÁ MULTIPLICANDO POR 2)
CREATE PROCEDURE TESTE1 
(@PARAMENTRO  INT OUTPUT)
AS 
SELECT @PARAMENTRO *2 
RETURN

DECLARE  @VALOR AS INT = 20
EXEC TESTE1 @VALOR OUTPUT
