-- UTILIZANDO CASE WHEN BANCO DE DADOS PedidosDB tabela produtos

SELECT DESCRICAO,QUANT_ESTOQUE,
CASE 
	WHEN 
		QUANT_ESTOQUE <= 10
	THEN 'ABAIXO DA MÉDIA'
END AS VERIFICACAO 
FROM PRODUTOS 

--USANDO ELSE
SELECT DESCRICAO, QUANT_ESTOQUE,
CASE	
	WHEN 
	QUANT_ESTOQUE <= 10
	THEN 'ABAIXO DA MÉDIA'
	ELSE 'MÉDIA'
END AS VERIFICACAO
FROM PRODUTOS
