-- ESTUDOS IF E ELSE 
DECLARE @NUMERO INT,
		@TEXTO VARCHAR(10)

SET @NUMERO = 20
SET @TEXTO = 'CINTHIA'

IF @NUMERO = 20
SELECT 'NÚMERO CORRETO'

IF @TEXTO = 'CINTHIA'
BEGIN --USA O BEGIN, POIS TEM MAIS LINHAS DE CODIGO NO IF OU ELSE
	SET @NUMERO = 30
	SELECT @NUMERO
	END;
ELSE
	BEGIN
	SET @NUMERO = 40
	SELECT 'NÚMERO INCORRETO'
	END;