-- ESTUDOS DE PROCEDURES COM PARAMETROS  USANDO A TABELA CLIENTES NO BANCO DE DADOS PEDIDOSDB

--CRIANDO UMA PROCEDURE COM PARAMENTRO 
-- SMALLINT SIGNIFICA PEGAR OS VALORES QUE JÁ EXIXSTEM NO BANCO DE DADOS
CREATE PROCEDURE CLIENTE_PARAMETRO
(@ID  SMALLINT)
AS
SELECT NOME,ENDERECO,CIDADE,BAIRRO FROM CLIENTES WHERE CODCLIENTE = @ID

EXEC CLIENTE_PARAMETRO 2

-- ALTERAR UMA PROCEDURE COLOCANDO PARAMENTROS 
-- ESSE PROCEDIMENTO É NECESSARIO EXECUTAR COM PASSANDO 2 PARAMENTROS, 1 INT 2 VARCHAR 
ALTER PROCEDURE TESTE
(@PARAMENTRO1 AS INT, 
@PARAMENTRO2 AS VARCHAR(20))
AS
SELECT @PARAMENTRO1 AS NUMERO, @PARAMENTRO2 AS NOME

EXEC TESTE 3, 'CINTHIA'

SELECT * FROM CLIENTES

