--PROCEDURE PARA VALIDAR OS ATRASOS NA DEVOLUCAO DE LIVRO DO BANCO BIBLIOTECA 
--EXEC SP_ValidarAtraso 1,1

CREATE PROCEDURE SP_ValidarAtraso
(
@DEVOLUCAO INT,
@DIAS_ATRASO INT
)
AS
BEGIN 


	SELECT DIAS_ATRASO = @DIAS_ATRASO FROM DEVOLUCAO WHERE CODDEVOLUCAO = @DEVOLUCAO 

	
IF (@DEVOLUCAO IS NULL)
	 BEGIN 
		 SELECT 'NÚMERO NÃO ENCONTRADO' AS RETORNO
	 END
ELSE IF (@DEVOLUCAO > 0 AND @DIAS_ATRASO =1)
	 BEGIN
		  SELECT 'DEVOLUÇÃO COM ATRASO' AS RETORNO
	 END
ELSE IF (@DIAS_ATRASO = 0)
	BEGIN
	SELECT 'DEVOLUÇÃO EM DIA' AS RETORNO
	END

END