CREATE TABLE CLIENTES
(CODCLI INT IDENTITY,
NOME VARCHAR(30) NOT NULL,
ENDERECO VARCHAR(40) NOT NULL,
CIDADE VARCHAR(40) NOT NULL,
FONE CHAR(9) NOT NULL,
CONSTRAINT PK_CODCLI PRIMARY KEY (CODCLI));

SELECT * FROM CLIENTES

CREATE TABLE PEDIDOS 
(NUMPED INT IDENTITY,
CLIENTE INT,
DATA_ENTREGA DATETIME NOT NULL,
TRANSPORT INT,
CONSTRAINT PK_NUMPED PRIMARY KEY (NUMPED),
CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE) REFERENCES CLIENTES (CODCLI),
CONSTRAINT FK_TRANSPORT FOREIGN KEY (TRANSPORT)  REFERENCES TRANSPORTADORA(CODTRA));

SELECT * FROM PEDIDOS

CREATE TABLE TRANSPORTADORA 
(CODTRA INT IDENTITY,
NOME VARCHAR(20) NOT NULL,
CONSTRAINT PK_CODTRA PRIMARY KEY (CODTRA));

SELECT * FROM TRANSPORTADORA

--INSERINDO VALORES NA TABELA CLIENTES 
INSERT INTO CLIENTES VALUES
( 'JOAO','AV.BARÃO','MAUA',45114820),
( 'CINTHIA','AV.PORTUGUAL','MAUA',45119520),
( 'PEDRO','AV.CENTRO','SANTO ANDRE',42114820),
( 'MARIA','AV.GOIAS','SÃO CAETANO',45114820),
( 'JOAO','AV.BARÃO','SÃO BERNARDO DO CAMPO',45114874);

--INSERINDO VALORES NA TABELA PEDIDOS 
INSERT INTO PEDIDOS VALUES
(1,'20191005',1),
(2,'20201010',2),
(3,'20191012',3),
(4,'20201018',4),
(5,'20191022',5);

--INSERINDO VALORES NA TABELA TRANSPORTADORA 
INSERT INTO TRANSPORTADORA VALUES
('ADEMIR COMERCIO'),
('ADEMIR COMERCIO'),
('ALFA TRANSPORTES'),
('AMAZON TRANSPORTES'),
('ALFA TRANSPORTES');

-- c) Selecionar todos os pedidos da transportadora ABC.
SELECT PEDIDOS.NUMPED, TRANSPORTADORA.NOME
FROM PEDIDOS INNER JOIN TRANSPORTADORA 
ON PEDIDOS.TRANSPORT = TRANSPORTADORA.CODTRA 
WHERE TRANSPORTADORA.NOME = 'ADEMIR COMERCIO';

-- d) Quantos pedidos existem para o cliente 2?
SELECT CLIENTES.NOME,PEDIDOS.NUMPED
FROM CLIENTES INNER JOIN PEDIDOS
ON CLIENTES.CODCLI = PEDIDOS.CLIENTE
WHERE CLIENTES.NOME = 'CINTHIA';

-- e) Qual o número do Pedido mais recente?
SELECT NUMPED,MIN(DATA_ENTREGA)FROM PEDIDOS GROUP BY NUMPED;

-- f) Temos quantos pedidos para a Transportadora ABC?
SELECT COUNT(PEDIDOS.NUMPED)
FROM PEDIDOS INNER JOIN TRANSPORTADORA
ON PEDIDOS.TRANSPORT = TRANSPORTADORA.CODTRA
WHERE TRANSPORTADORA.NOME = 'ALFA TRANSPORTES';

-- g) Quantos Clientes residem em Mauá?
SELECT COUNT(CLIENTES.CIDADE) 
FROM CLIENTES WHERE CLIENTES.CIDADE = 'MAUA';

-- h) Selecionar Número do Pedido, Data_Entrega e Nome do Cliente.
SELECT PEDIDOS.NUMPED, PEDIDOS.DATA_ENTREGA, CLIENTES.NOME
FROM PEDIDOS INNER JOIN CLIENTES
ON PEDIDOS.CLIENTE = CLIENTES.CODCLI;

-- i) Selecionar Número do Pedido, Nome do Cliente e nome da Transportadora.
SELECT PEDIDOS.NUMPED, CLIENTES.NOME, TRANSPORTADORA.NOME
FROM PEDIDOS INNER JOIN CLIENTES
ON PEDIDOS.CLIENTE = CLIENTES.CODCLI
INNER JOIN TRANSPORTADORA
ON PEDIDOS.TRANSPORT = TRANSPORTADORA.CODTRA;

-- j) Selecionar todos os clientes da cidade de Santo André, Mauá e SBC.
SELECT * FROM CLIENTES
WHERE CIDADE IN('MAUÁ', 'SANTO ANDRÉ', 'SÃO BERNARDO DO CAMPO');







