CREATE TABLE PRODUTO
(CODPROD INT IDENTITY,
UNIDADE CHAR(3) NOT NULL,
DESCRICAO CHAR(20) NOT NULL,
VALOR_UNIT NUMERIC(9,2) NOT NULL,
DATA_CAD DATETIME NOT NULL,
CONSTRAINT PK_COD PRIMARY KEY(CODPROD));

INSERT INTO PRODUTO VALUES ('1','TINTA PVC', 15.80,'20160052');
SELECT * FROM PRODUTO;

INSERT INTO PRODUTO(CODPROD,DESCRICAO) VALUES ('MASSA CORRIDA');

--ALTERAR O PRECO DA TINTA PVC PARA 15.80
UPDATE PRODUTO
SET VALOR_UNIT=14.9
WHERE DESCRICAO='MASSSA CORRIDA';

-- REAJUSTE APLICAR 5% ACRESCIMO

UPDATE  PRODUTO
SET VALOR_UNIT=(VALOR_UNIT*1.05);

-- APLICAR DESCONTO 5%
UPDATE PRODUTO
SET VALOR_UNIT=(VALOR_UNIT-0.95);

-- ELIMINAR REGISTROS
DELETE FROM PRODUTO;

-- ELIMINAR TODOS OS PRODUTOS COM VALOR INFERIOR A 5.0 
DELETE FROM PRODUTO
WHERE VALOR_UNIT<5;
