CREATE TABLE ASSOCIADOS

(CODASSOC INT IDENTITY,
NOME VARCHAR(40)NOT NULL,
APELIDO VARCHAR(20)NOT NULL,
PAIS VARCHAR (10)NOT NULL,
REGIAO CHAR(25)NOT NULL,
ESTADO CHAR(2)NOT NULL,
CIDADE VARCHAR(20)NOT NULL,
EMAIL VARCHAR(30)NOT NULL,
SEXO CHAR(1)NOT NULL,
DATA_NASC DATETIME NOT NULL,
DATA_CAD DATETIME NOT NULL,
CONSTRAINT PK_CODASSOC PRIMARY KEY(CODASSOC));

SELECT * FROM ASSOCIADOS

CREATE TABLE ASSOCGRUPO
(CODGRUPO INT IDENTITY,
CODASSOC INT,
PONTOS INT NOT NULL,
CONSTRAINT FK_CODGRUPO FOREIGN KEY(CODGRUPO) REFERENCES GRUPOS(CODGRUPO),
CONSTRAINT FK_CODASSOC FOREIGN KEY(CODASSOC) REFERENCES ASSOCIADOS(CODASSOC));

SELECT * FROM ASSOCGRUPO

CREATE TABLE GRUPOS
(CODGRUPO INT IDENTITY,
CODGAME INT,
DATAINI DATETIME NOT NULL,
DATAFIM DATETIMENOT NULL,
MAXPART INT NOT NULL,
CONSTRAINT PK_CODGRUPO PRIMARY KEY(CODGRUPO),
CONSTRAINT FK_CODGAME FOREIGN KEY(CODGAME) REFERENCES GAMES(CODGAME));

SELECT * FROM GRUPOS

CREATE TABLE GENERO
(CODGEN INT IDENTITY,
NOME VARCHAR(40) NOT NULL,
CONSTRAINT PK_CODGEN PRIMARY KEY(CODGEN));

SELECT * FROM GENERO

CREATE TABLE GAMES 
(CODGAME INT,
NOME VARCHAR (20),
GENERO INT,
IDADELIM INT,
CONSTRAINT PK_CODGAME PRIMARY KEY(CODGAME),
CONSTRAINT FK_GENERO FOREIGN KEY(GENERO)
REFERENCES GENERO(CODGEN));

SELECT * FROM GAMES


--b) Inserir 5 registros em cada tabela;

INSERT INTO ASSOCIADOS VALUES 
('PATRICIA','PATY','BRASIL','SÃO PAULO','SP','SÃO CAETANO','PATRICIA01@GMAIL.COM','F','05051981','10052010'),
('CINTHIA', 'CI' ,'BRASIL','SÃO PAULO','SP','MAUÁ','CINTHIABS1@GMAIL.COM','F','31011999','10102010'),
('MARIA','MARI','PORTUGUAL','LISBOA','PL','LISBOA','MARIA001@GMAIL.COM','F','20051985','10052011'),
('JOAO','JOAO','BRASIL','RIO DE JANEIRO','RJ','IPANEMA','JOAO001@GMAIL.COM','M','05051991','10052012'),
('BIANCA','BIA','BRASIL','SÃO PAULO','SP','SANTO ANDRE','BIANCA01@GMAIL.COM','F','05051999','10082012');

INSERT INTO ASSOCGRUPO VALUES
(1,10),
(2,9),
(3,20),
(4,6),
(5,15);

INSERT INTO GRUPOS VALUES
(1,'05052020','07072020',1),
(2,'05052020','20062020',4),
(3,'05052020','15062020',5),
(4,'05052020','17062020',6),
(5,'05052020','07062020',4);

INSERT INTO GENERO VALUES
(1,'CORRIDA'),
(2,'AÇÃO'),
(3,'AÇÃO'),
(4, 'CARTAS'),
(5, 'AVENTURA');

INSERT INTO GAMES VALUES
('MAX',1,6),
('CATGRUP',2,2),
('GRUPO01',3,7),
('GRUPO02',4,4),
('RUN',5,6);

--c) Quantos associados existem no Brasil?
SELECT COUNT(ASSOCIADOS.PAIS)FROM ASSOCIADOS WHERE ASSOCIADOS.PAIS ='BRASIL';

--d) Listar Código do Grupo e Nome do Associado.
SELECT GRUPOS.CODGRUPO, ASSOCIADOS.NOME
FROM GRUPOS INNER JOIN ASSOCIADOS ON GRUPOS.CODGRUPO=CODGRUPO INNER JOIN ASSOCGRUPO ON GRUPOS.CODGRUPO=NOME

--e) Listar Código do Game, Nome do Game e Descrição do Gênero (nome).
SELECT GAMES.CODGAME, GAMES.NOME, GENERO.NOME
FROM GAMES INNER JOIN GENERO ON GAMES.CODGAME=GAMES.NOME INNER JOIN ASSOCGRUPO ON GENERO.NOME=GENERO;

--Listar todos os associados, independentemente se estejam participando de algum grupo ou não;
SELECT * FROM ASSOCIADOS WHERE ASSOCIADOS.NOME =(SELECT MAX(ASSOCIADOS.DATA_CAD) FROM ASSOCIADOS)

--g) Listar todos os associados com data de cadastro igual à mais recente.
SELECT * FROM ASSOCIADOS WHERE ASSOCIADOS.DATA_CAD >=(SELECT MAX(ASSOCIADOS.DATA_CAD) FROM ASSOCIADOS)
--h) Quantos games temos do gênero ‘ação’ ?
SELECT COUNT(GENERO.NOME) AS 'GENERO AÇÃO' FROM GENERO WHERE GENERO.NOME='AÇÃO';

--i) Quantos associados “M” (masculinos) existem no cadastro?
SELECT ASSOCIADOS.NOME AS 'MASCULINO' FROM ASSOCIADOS
WHERE ASSOCIADOS.SEXO='M';
