CREATE TABLE CDS
(CODIGO INT IDENTITY,
NOME VARCHAR(30)NOT NULL,
DATA_COMPRA DATETIME NOT NULL,
VALOR_PAGO NUMERIC(10,2) NOT NULL,
LOCAL_COMPRA VARCHAR(20) NOT NULL,
ALBUM INT NOT NULL,
CONSTRAINT PK_CDS PRIMARY KEY(CODIGO));


INSERT INTO CDS VALUES 
('PITTY','2020-01-13', 22,0 , 'AMERICANAS',1),
 ('BON JOVI','2020-03-03', 32,0 , 'SARAIVA',2),
('RITA LEE','2020-02-11', 39,0 , 'SARAIVA',2),
 ('OASIS','2020-01-03', 32,0 , 'SUBMARINO',4),
('BEATLES','2020-01-22', 50,0 , 'CARREFOUR',3);
SELECT * FROM CDS;

-- MOSTRAR OS CAMPOS NOME E DATA
SELECT NOME,DATA_COMPRA FROM CDS;

--MOSTRAR O TOTAL GASTO COM A COMPRA DOS CDS
SELECT SUM(VALOR_PAGO)AS'TOTAL GASTO' FROM CDS;

-- MOSTRAR A QUANTIDADE DE CDS
SELECT COUNT(CODIGO)AS'QUANTIDADE' FROM CDS;

-- MOSTRAR O NOME DE TODOS OS CDS COMPRADOS NO SUBMARINO
SELECT NOME FROM CDS WHERE LOCAL_COMPRA = 'SUBMARINO';

-- MOSTRAR TODOS OS CDS QUE SÃO ALBUMS
SELECT * FROM CDS WHERE ALBUM = 1;

--MOSTRAR O CD QUE CUSTOU MAIS CARO
SELECT * FROM CDS WHERE VALOR_PAGO =(SELECT MAX(VALOR_PAGO)FROM CDS);

--MOSTRAR TODOS OS CDS QUE TEM NOME INICIADO PELA LETRA R
SELECT * FROM CDS WHERE NOME LIKE'R%';

--MOSTRAR A MEDIA DE PREÇOS DOS CDS
SELECT AVG(VALOR_PAGO)AS 'MEDIA' FROM CDS;

--QUANTOS CDS FORAM COMPRADOS NA AMERICANAS
SELECT * FROM CDS WHERE LOCAL_COMPRA = 'AMERICANAS';

--ATUALIZAR O PREÇO DOS CDS REAJUSTANDO EM 10%;
UPDATE CDS
SET VALOR_PAGO = VALOR_PAGO*1.10;

--MOSTRAR TODOS OS CDS COMPRADOS NO SUBMARINO, AMERICANAS E SARAIVA
SELECT*FROM CDS WHERE LOCAL_COMPRA IN('AMERICANAS','SARAIVA','SUBMARINO');

--MOSTRAR TODOS OS CDS COM CODIGO ENTRE 20 E 30 INCLUSIVE.
SELECT*FROM CDS WHERE CODIGO BETWEEN 20 AND 30;

--MOSTRAR TODOS OS CDS CUJO VALOR PAGO SEJA MAIOR QUE 25,00
SELECT*FROM CDS WHERE VALOR_PAGO>25;

-- MOSTRAR O PREÇO DO CD MAIS BARATO
SELECT MIN(VALOR_PAGO) AS 'CDS MAIS BARATO'FROM CDS;

--MOSTRAR TODOS OS LOCAIS DE COMPRA SEM DUPLICIDADE
SELECT DISTINCT LOCAL_COMPRA FROM CDS;

--SELECIONAR TOODS COM O VALOR PAGO ACIMA DA MEDIA
SELECT*FROM CDS WHERE VALOR_PAGO>(SELECT AVG(VALOR_PAGO)FROM CDS);
--SELECIONAR TODAS AS DATA DE COMPRA IGUAL A DATA MAIS RECENTE
SELECT*FROM CDS WHERE DATA_COMPRA = (SELECT MAX(DATA_COMPRA)FROM CDS);
-- QUANTOS CDS ESTÃO COM VALOR_PAGO ABAIXO DA MEDIA?
SELECT COUNT(*) AS 'VALOR ABAICO DA MEDIA' FROM CDS WHERE VALOR_PAGO<(SELECT AVG(VALOR_PAGO)FROM CDS);
--SELECIONAR TODOS COM DARA DA COMPRA IGUAL A DATA MAIS ANTIGA.
SELECT*FROM CDS WHERE DATA_COMPRA=(SELECT MIN(DATA_COMPRA)FROM CDS);